### PR TITLE
wrangler & miniflare dependencies as optional peerDependencies

### PR DESCRIPTION
**Pull request by arisris**
This is my first **PR**. I want join to the honojs community.

Since dev-server is not required to use cloudflare adapter, 
as it so i try to move miniflare dependencies into devDependencies and add them into optional peerDependencies including wrangler.

also i try to add bun & node adapter.

Thankyou

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @arisris !

Thank you for your first PR! I want to review it, but can you separate this PR to the 3 PRs?

1. Removing `miniflare` deps.
2. Bun adapter.
3. Node.js adapter.

**Comment by arisris** [comment]
@yusukebe Thanks. I will do it tomorow. After done i will close this PR

**Comment by arisris** [comment]
I have separate this with 3 PRs
https://github.com/honojs/vite-plugins/pull/165
https://github.com/honojs/vite-plugins/pull/166
https://github.com/honojs/vite-plugins/pull/167

**Comment by yusukebe** [comment]
@arisris 

Thanks! I'll see them later.

**Pull request closed without merging**
