### PR TITLE
feat(dev-server): leverage vite error handling

### PR DESCRIPTION
**Pull request by marbemac**
**TODO**

Requires https://github.com/honojs/node-server/pull/131.

- [x] de-yalc `@hono/node-server` once a new version with the custom error handler option is published

---

This PR adjusts the dev server so that it passes errors / unexpected conditions through to Vite. This allows us to take advantage of the standard Vite error overlays, stack traces, etc.

**Before**

Screenshot 2024-01-26 at 10 25 48 AM

**After**

Screenshot 2024-01-26 at 10 26 29 AM

Or if an error object is returned from the hono endpoint, stack trace is included.:

Screenshot 2024-01-26 at 10 38 09 AM

This is really helpful when rendering client apps in order to get the original stack trace and nice overlay for SSR errors, for example:

```tsx
/**
 * The frontend app
 */
honoApp.get('*', async c => {
  try {
    // react, solid, etc
    const app = await renderClientApp(<App />);

    return new Response(app, { headers: { 'Content-Type': 'text/html' } });
  } catch (err: any) {
    // in dev, pass the error back to the vite dev server to display in the error overlay
    if (import.meta.env.DEV) return err;

    throw err;
  }
});
```

### CODE REVIEW

**Comment by marbemac** [comment]
updated to use @hono/node-server v1.7

**Comment by yusukebe** [comment]
Hi @marbemac 

Nice! One thing. Could you run `yarn changeset`? This is a "minor bump".

**Comment by marbemac** [comment]
sure thing - all set

**Comment by yusukebe** [comment]
@marbemac 

Thank! Let's go!

**Pull request merged**
