### PR TITLE
Add css to the dev server exclude defaults

### PR DESCRIPTION
**Pull request by emirotin**
As suggested in https://github.com/honojs/hono/issues/2286#issuecomment-1974825744

@yusukebe I am not sure if I did the right thing with the changeset, please check :)

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @emirotin 

Did you run a `yarn changeset` command on the top of the project?

**Comment by emirotin** [comment]
> Hi @emirotin
> 
> Did you run a `yarn changeset` command on the top of the project?

Yes, this is how `.changeset/bright-laws-begin.md` file was generated

**Comment by yusukebe** [comment]
@emirotin 

Thanks. But the bot can't detect the changeset. Please try again. Remove `.changeset/bright-laws-begin.md` and re-run `yarn changeset`.

**Comment by emirotin** [comment]
@yusukebe I will close this one and open another PR

**Pull request closed without merging**
