### PR TITLE
fix(dev-server): Move miniflare,wrangler to dev as it peer optional

### PR DESCRIPTION
**Pull request by arisris**
Since dev-server is not required to use cloudflare adapter,
as it so i try to move miniflare dependencies into devDependencies and add them into optional peerDependencies including wrangler.

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @arisris 

Looks good! I'd like you to do two things:

* Add a description about installing `miniflare` and `wrangler` for the Cloudflare Adapter on the `README.md`.
* Run `yarn changeset` on the top of the project to generate a changeset file. This is a `patch` change. And push it.

**Comment by arisris** [comment]
@yusukebe Sure, do i have to create new PRs again like before?

**Comment by yusukebe** [comment]
Hi @arisris 

> Sure, do i have to create new PRs again like before?

No! Please update this PR.

**Comment by yusukebe** [comment]
Hey @arisris !

Thank you for handling it. I've done the other remaining things. It looks good! Let's go with it.

**Pull request merged**
