### PR TITLE
feat(dev-server): support `c.env.ASSETS` for CF Pages

### LINKED ISSUE #17: `c.env.ASSETS` is `undefined` in dev server
I'm migrating one of my projects from Workers Site to Pages with Functions, and having trouble with `env.ASSETS.fetch`. With the following setup (I'll publish a reproduction repo later), `GET /` returns a 500 error saying `TypeError: Cannot read properties of undefined (reading 'fetch')` during dev server (i.e., `wrangler pages dev -- vite`).

```ts
// src/index.ts
import { Hono } from "hono";

const app = new Hono().get("/", async (c) => {
  const env = c.env as { ASSETS: { fetch: typeof fetch } };
  const asset = await env.ASSETS.fetch(
    new URL("/assets/static.json", c.req.url)
  ).then((r) => r.json());
  return c.json({ asset });
});

export default app;
```

```jsonc
// public/assets/static.json
{
  "foo": "Hello world",
  "bar": 42
}
```

```jsonc
// public/_routes.json
{
  "version": 1,
  "include": ["/*"],
  "exclude": ["/assets/*"]
}
```

```ts
// vite.config.ts
import { type UserConfig } from "vite";
import pages from "@hono/vite-cloudflare-pages";
import devServer, { defaultOptions } from "@hono/vite-dev-server";

export default {
  plugins: [
    pages(),
    devServer({
      exclude: [...defaultOptions.exclude, /^\/assets\/.+/],
    }),
  ],
} satisfies UserConfig;
```

After building with `vite build`, however, `GET /` returns the expected `{"asset":{"foo":"Hello world","bar":42}}` during preview server with `wrangler pages dev dist`. So how can I bind `env.ASSETS.fetch` to Hono's context in dev mode? If it's already possible, a small documentation would be much appreciated (I tried to find relevant options in the two plugins but wasn't successful unfortunately)

### PR DESCRIPTION
**Pull request by yusukebe**
Resolves #17

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @yudai-nkt!

I was able to fix the `env.ASSET.fetch` issue with this PR. Could you review it?

**Comment by yudai-nkt** [comment]
that's cool thanks! i'm afraid i won't have time right now, but will check this on the weekend.

**Comment by yudai-nkt** [comment]
I tried this fix with the reproduction repo in https://github.com/honojs/vite-plugins/issues/17#issuecomment-1783230087, but unfortunately I'm still getting the following error:

```
✘ [ERROR] Error: Could not proxy request: TypeError: fetch failed

      at
  /Users/ynkt/src/github.com/yudai-nkt/hono-vite-plugin-with-env-assets/node_modules/wrangler/wrangler-dist/cli.js:108453:29
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async #handleLoopbackCustomService
  (/Users/ynkt/src/github.com/yudai-nkt/hono-vite-plugin-with-env-assets/node_modules/miniflare/dist/src/index.js:7798:24)
      at async #handleLoopback
  (/Users/ynkt/src/github.com/yudai-nkt/hono-vite-plugin-with-env-assets/node_modules/miniflare/dist/src/index.js:7842:20)
```

Vite config is as follows:

```ts
import { type UserConfig } from "vite";
import pages from "@hono/vite-cloudflare-pages";
import { defaultOptions } from "@hono/vite-dev-server";

// copied from packages/dev-server/src/dev-server.ts in this PR
import { devServer } from "./plugin";

export default {
  plugins: [
    pages(),
    devServer({
      exclude: [...defaultOptions.exclude, /^\/assets\/.+/],
      cf: { assets: true }
    }),
  ],
} satisfies UserConfig;
```

**Comment by yusukebe** [comment]
@yudai-nkt

Weird. I've cloned it and tried to run it with this PR's version, and it works fine.

Screenshot 2023-11-12 at 21 17 42

By the way, I used the `vite dev` command without `wrangler`. Could you try it again?

**Comment by yudai-nkt** [comment]
Uh, I was using `wrangler pages dev -- vite` and port 8788. `vite dev` and port 5173 work fine, thanks! IIUC, we don't need to directly call `wrangler` during development because the plugin takes care of binding and other stuff, is that correct?

**Comment by yusukebe** [comment]
Great!

> IIUC, we don't need to directly call `wrangler` during development because the plugin takes care of binding and other stuff, is that correct?

Yes, we should use only Vite.

**Comment by yusukebe** [comment]
Okay! I'll ship it now.

**Comment by yudai-nkt** [comment]
Hi @yusukebe, it looks like you published this PR as [`@hono/cloudflare-pages@v0.1.0`](https://github.com/honojs/vite-plugins/releases/tag/%40hono%2Fcloudflare-pages%40v0.1.0) but it should be `@hono/vite-cloudflare-pages` I suppose.

**Comment by yusukebe** [comment]
Hi, @yudai-nkt .

Ah! The tag name was wrong! But, the npm package name is correct: https://www.npmjs.com/package/@hono/vite-cloudflare-pages. So you can use the `v0.1.0` now.

**Comment by yudai-nkt** [comment]
sorry, i meant `@hono/vite-dev-server` instead of cloudflare pages. latest release doesn't seem to include this pr: https://www.npmjs.com/package/@hono/vite-dev-server

**Comment by yusukebe** [comment]
@yudai-nkt 

Super sorry! I've published `v0.2.0` of `@hono/vite-dev-server`, now.

**Comment by yudai-nkt** [comment]
thanks, I'll try it tonight!

**Pull request merged**
